### ISSUE TITLE
A new release for Swift 3.0

### ISSUE THREAD

**Issue by devxoul** [cezheng/PySwiftyRegex#6]
Xcode 8 and Swift 3.0 is released, and it's time to make a new release of PySwiftyRegex for Swift 3 :tada:

**Comment by cezheng** [comment]
@devxoul Hi, I just released for Swift 3. :beers: 

Since I don't speak Korean I used Google Translate to add a line in the Korean README, is that correct?

> Swift 2.3의 경우 버전 0.3.0를 이용해주십시오.

**Comment by devxoul** [comment]
@cezheng, Thanks! That translation is perfect 👍
