### ISSUE TITLE
How to get function name given match string?

### ISSUE THREAD

**Issue by steve21124** [cezheng/PySwiftyRegex#8]
For example : https://gist.github.com/steve21124/c13c9203f1e5280611335032ada65a41
1. match string "ImageStack.Notifications.stackDidReload" return "func subscribe()"
2.match string "self.cameraController.takePicture" return "takePicture()"

is possible using this to get above?

**Comment by cezheng** [comment]
This is just general regex question rather than an issue of this project. I suggest you to ask this on StackOverflow.
